### PR TITLE
Jeff/update hooks

### PR DESCRIPTION
**Pull request by sofuture**
using new hooks format + resources

### CODE REVIEW

**Comment by r0mant** [comment]
Do you really need a dedicated bootstrap container now? As far as I see you just use `kubectl create` so you should be good with just using the default `hook:0.0.1` image. It provides `/usr/local/bin/kubectl`.

**Comment by sofuture** [comment]
Good point, I'll fix.

**Comment by r0mant** [comment]
lgtm

@sofuture Thanks for taking care of this!

**Comment by alexey-medvedchikov** [comment]
Works for me

**Pull request merged**
